[en]
    languageName = "English"
    contentDir = "content/en"
    weight = 1
    [en.params.head]
        tagline = "Exploring Tokyo"
    [en.params.feature]
        message = "Welcome to Tokyo Rambler!"
        tagline = "A newsletter highlighting fun things to do in Tokyo."
        link = "/en/about"
        caption = "About"
    [en.params.footer]
        license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Follow me"
        socialCaption = "Exploring Tokyo your way"

[nl]
    languageName = "Nederlands"
    contentDir = "content/nl"
    weight = 2
    [nl.params.head]
        tagline = "Een Hugo Thema"
    [nl.params.feature]
        message = "Welkom bij Hinode!"
        tagline = "Een documentatie en blog thema voor Hugo gebaseerd op Bootstrap 5."
        link = "/nl/over-mij"
        caption = "Over mij"
    [nl.params.footer]
        license = "Gelicenseerd onder Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank'>CC BY-NC-SA 4.0</a>)."
        socialTitle = "Volg mij"
        socialCaption = "Ik doe aan programmeren en tweet memes"