[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Things to do"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Neighborhoods"
  url = "/neighborhoods/"
  weight = 30

[[main]]
  name = "Asakusa"
  url = "/en/neighborhoods/asakusa/"
  parent = "Neighborhoods"
  weight = 1

[[main]]
  name = "Ueno"
  url = "/en/neighborhoods/ueno/"
  parent = "Neighborhoods"
  weight = 2

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 40

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "<i class=\"fab fa-medium fa-2x\"></i>"
  url = "https://medium.com/"
  weight = 30

[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10

